# Site settings
title: "colin"
description: >-
  I bought a vanity domain and had to figure something to put here
timezone: America/Halifax
image: assets/img/prankeapple.gif
repo: https://github.com/colindougl.as
mode: dark # default theme "dark" | "light"
navbar: icons # either "icons" or "text"

# Profile settings
author:
  name: Colin Douglas
  bio: Data science and chemistry-ish
  username: colindouglas
  github: colindouglas
  linkedin: colinddouglas
  twitter: colindouglas
  email: me@colindougl.as
  phone: (902) 418-5666
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://colindougl.as"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

scholar:
  style: apa
  bibliography_list_tag: ul

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
